/*
 * @i18nhero/public-api
 *
 * Public api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::public_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOrganizations403Response {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "statusCode")]
    pub status_code: f64,
}

impl GetOrganizations403Response {
    pub fn new(message: String, status_code: f64) -> GetOrganizations403Response {
        GetOrganizations403Response {
            message,
            status_code,
        }
    }
}
