/*
 * @i18nhero/public-api
 *
 * Public api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::public_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Organization {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "allow_ai_translations")]
    pub allow_ai_translations: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: String,
}

impl Organization {
    pub fn new(
        _id: String,
        title: String,
        allow_ai_translations: bool,
        created_at: String,
        modified_at: String,
    ) -> Organization {
        Organization {
            _id,
            title,
            allow_ai_translations,
            created_at,
            modified_at,
        }
    }
}
