/*
 * @i18nhero/public-api
 *
 * Public api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::public_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialExportProjectConfigInput {
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<models::FileFormat>,
    #[serde(rename = "flat", skip_serializing_if = "Option::is_none")]
    pub flat: Option<bool>,
    #[serde(rename = "keep_empty_fields", skip_serializing_if = "Option::is_none")]
    pub keep_empty_fields: Option<bool>,
}

impl PartialExportProjectConfigInput {
    pub fn new() -> PartialExportProjectConfigInput {
        PartialExportProjectConfigInput {
            format: None,
            flat: None,
            keep_empty_fields: None,
        }
    }
}
