/*
 * @i18nhero/public-api
 *
 * Public api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::public_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PushLocaleInput {
    #[serde(rename = "files")]
    pub files: Vec<models::PushLocaleInputFile>,
}

impl PushLocaleInput {
    pub fn new(files: Vec<models::PushLocaleInputFile>) -> PushLocaleInput {
        PushLocaleInput { files }
    }
}
