version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
  - package-ecosystem: cargo
    directory: /packages/i18nhero
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
  - package-ecosystem: cargo
    directory: /packages/i18nhero-codegen
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
