version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 100
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 100
  - package-ecosystem: cargo
    directory: /packages/autoi18n
    schedule:
      interval: monthly
    open-pull-requests-limit: 100
  - package-ecosystem: cargo
    directory: /packages/autoi18n-config
    schedule:
      interval: monthly
    open-pull-requests-limit: 100
