[package]
name = "autoi18n-config"
description = "Config for autoi18n"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true

[features]
default = []
json-schema = ["dep:schemars"]

[dependencies]
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
