[package]
name = "i18nhero-codegen"
publish = false
description = "Code generation for the i18nhero cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true

[dependencies]
anyhow.workspace = true
i18nhero.workspace = true
regex.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
