/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProjectWebhookInput {
    #[serde(rename = "triggers")]
    pub triggers: Vec<models::ProjectWebhookEvent>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl CreateProjectWebhookInput {
    pub fn new(
        triggers: Vec<models::ProjectWebhookEvent>,
        description: String,
        url: String,
        enabled: bool,
    ) -> CreateProjectWebhookInput {
        CreateProjectWebhookInput {
            triggers,
            description,
            url,
            enabled,
        }
    }
}
