/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTranslationInput {
    #[serde(rename = "locales")]
    pub locales: std::collections::HashMap<String, String>,
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "description")]
    pub description: String,
}

impl CreateTranslationInput {
    pub fn new(
        locales: std::collections::HashMap<String, String>,
        identifier: String,
        description: String,
    ) -> CreateTranslationInput {
        CreateTranslationInput {
            locales,
            identifier,
            description,
        }
    }
}
