/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailMissingVerification {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "email")]
    pub email: String,
}

impl EmailMissingVerification {
    pub fn new(_id: String, email: String) -> EmailMissingVerification {
        EmailMissingVerification { _id, email }
    }
}
