/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationProjectOverview {
    #[serde(rename = "projects")]
    pub projects: f64,
    #[serde(rename = "total_identifiers")]
    pub total_identifiers: f64,
}

impl OrganizationProjectOverview {
    pub fn new(projects: f64, total_identifiers: f64) -> OrganizationProjectOverview {
        OrganizationProjectOverview {
            projects,
            total_identifiers,
        }
    }
}
