/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationMember {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "full_name")]
    pub full_name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "profile_image_url")]
    pub profile_image_url: String,
}

impl OrganizationMember {
    pub fn new(
        user_id: String,
        full_name: String,
        email: String,
        profile_image_url: String,
    ) -> OrganizationMember {
        OrganizationMember {
            user_id,
            full_name,
            email,
            profile_image_url,
        }
    }
}
