/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalAccessToken {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "secret")]
    pub secret: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl PersonalAccessToken {
    pub fn new(
        _id: String,
        secret: String,
        user_id: String,
        description: String,
        created_at: String,
    ) -> PersonalAccessToken {
        PersonalAccessToken {
            _id,
            secret,
            user_id,
            description,
            created_at,
        }
    }
}
