/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PushLocaleInputFile {
    #[serde(rename = "file_format")]
    pub file_format: models::FileFormat,
    #[serde(rename = "file_name")]
    pub file_name: String,
    #[serde(rename = "content")]
    pub content: String,
}

impl PushLocaleInputFile {
    pub fn new(
        file_format: models::FileFormat,
        file_name: String,
        content: String,
    ) -> PushLocaleInputFile {
        PushLocaleInputFile {
            file_format,
            file_name,
            content,
        }
    }
}
