/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshAuthTokensInput {
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
}

impl RefreshAuthTokensInput {
    pub fn new(refresh_token: String) -> RefreshAuthTokensInput {
        RefreshAuthTokensInput { refresh_token }
    }
}
