/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Translation {
    #[serde(rename = "locales")]
    pub locales: std::collections::HashMap<String, String>,
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "project_id")]
    pub project_id: String,
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: String,
    #[serde(rename = "deleted_at", deserialize_with = "Option::deserialize")]
    pub deleted_at: Option<String>,
}

impl Translation {
    pub fn new(
        locales: std::collections::HashMap<String, String>,
        _id: String,
        organization_id: String,
        project_id: String,
        identifier: String,
        description: String,
        created_at: String,
        modified_at: String,
        deleted_at: Option<String>,
    ) -> Translation {
        Translation {
            locales,
            _id,
            organization_id,
            project_id,
            identifier,
            description,
            created_at,
            modified_at,
            deleted_at,
        }
    }
}
