/*
 * @i18nhero/web-api
 *
 * Api for i18nhero.com
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::codegen::web_api::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProjectInput {
    #[serde(rename = "localizations")]
    pub localizations: Vec<models::UpdateProjectInputLocalization>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "is_public")]
    pub is_public: bool,
}

impl UpdateProjectInput {
    pub fn new(
        localizations: Vec<models::UpdateProjectInputLocalization>,
        title: String,
        description: String,
        is_public: bool,
    ) -> UpdateProjectInput {
        UpdateProjectInput {
            localizations,
            title,
            description,
            is_public,
        }
    }
}
