[package]
name = "i18nhero"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true

[package.metadata.wix]
upgrade-guid = "6F9AFD36-B151-4A3E-AFDD-154307A499CF"
path-guid = "E203BA21-081C-408B-9395-A7223571469A"
license = false
eula = false

[features]
default = []
json-schema = ["dep:schemars"]

[dependencies]
bytes.workspace = true
clap.workspace = true
clap_complete.workspace = true
console.workspace = true
dialoguer.workspace = true
dirs.workspace = true
git2.workspace = true
json_comments = "0.2.2"
reqwest.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
supports-hyperlinks.workspace = true
terminal-link.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
