[package]
name = "i18nhero"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
categories.workspace = true

[package.metadata.wix]
upgrade-guid = "6F9AFD36-B151-4A3E-AFDD-154307A499CF"
path-guid = "E203BA21-081C-408B-9395-A7223571469A"
license = false
eula = false

[dependencies]
i18nhero-config = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
json5 = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yml = { workspace = true }
