name: release cargo
on:
  push:
    tags: ["*"]
  workflow_dispatch:
jobs:
  release_cargo:
    name: Publish to cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Publish cli
        run: cargo publish -p i18nhero --verbose --locked --token ${{ secrets.CARGO_TOKEN }}
